# Užduotys
**Atkreipkite dėmesį, kad, jeigu neteisingai įvsite atsakymą, Out reikšmė irgi pasikeis**

In [13]:
import numpy as np

1\. Sukurkite vektorių su skaičiais nuo 1 iki 9

In [17]:
sarasas = range(1, 10)
vector = np.array(sarasas)
vector
# print(vector)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2\. Sukurkite vektorių iš 10 nulių

In [19]:
v_nuliai = np.zeros(10)
v_nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [30]:
v_vienetai = np.ones(10)
v_vienetai


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4\. Sukurkite vektorių iš 10 ketvertų

In [37]:
v_ketvirtukai = np.ones(10)*4
v_ketvirtukai

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [38]:
kas_2_iki100 = np.arange(0, 101, 2)
kas_2_iki100

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [51]:
sar = np.arange(1,26)
sar_5x5 = sar.reshape(5,5)
sar_5x5


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

7\. Iš matricos ištraukite skaičių 12

In [53]:
print(sar[11])

12


12

8\. Iš matricos ištraukite paskutinę eilutę.

In [69]:
pask_eilute = sar_5x5[4:]
pask_eilute

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

9\. Iš matricos ištraukite submatricą

1, 2, 3  
6, 7, 8  
11,12,13

In [73]:
eilute_3x3 = sar_5x5[:3, :3]
eilute_3x3

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10  
12, 13, 14, 15  
17, 18, 19, 20

In [83]:
eilute_4x3 = sar_5x5[1:4, 1::]
eilute_4x3

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [85]:
eilute_2x3 = sar_5x5[3:, :3]
eilute_2x3

array([[16, 17, 18],
       [21, 22, 23]])

array([[16, 17, 18],
       [21, 22, 23]])

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [112]:
vektorius = np.random.rand(20)
vektorius

array([0.88771019, 0.84904035, 0.92352729, 0.92130968, 0.57947738,
       0.05289977, 0.31417048, 0.96817084, 0.96068471, 0.14343945,
       0.67410703, 0.55599048, 0.37757934, 0.85800133, 0.06353334,
       0.61958889, 0.1777505 , 0.17076954, 0.42296446, 0.29001693])

array([0.8583063 , 0.7839858 , 0.15307399, 0.74393181, 0.13574434,
       0.36289168, 0.13960192, 0.18715374, 0.29947662, 0.7245185 ,
       0.06837904, 0.44806807, 0.31655348, 0.21103823, 0.6815801 ,
       0.81323892, 0.48069123, 0.57937349, 0.72240019, 0.65220459])

13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [118]:
vekt_max = vektorius.max()
vekt_max

0.9681708440530854

0.8583063020360838

In [120]:
vekt_max_index = vektorius.argmax()
vekt_max_index

7

0

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [121]:
vekt_min = vektorius.min()
vekt_min

0.052899765652055786

0.06837904455958688

In [122]:
vekt_min_index = vektorius.argmin()
vekt_min_index

5

10

15\. Atspausdinkite šios matricos duomenų tipą

In [125]:
vekt_type = vektorius.dtype
vekt_type

dtype('float64')

dtype('float64')

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [128]:
matrix_int = np.arange(1, 101)
matrix_int

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [130]:
daugiau_90 = matrix_int[ matrix_int > 90]
daugiau_90

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

17\. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [132]:
dalynasi_is_7 = matrix_int[ matrix_int % 7 == 0]
dalynasi_is_7

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

18\. Sukurkite tokią matricą:

In [55]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [144]:
new_matrix = np.arange(0.025, 1.025, 0.025)
new_matrix
new_matrix.reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

19\. sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [74]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [338]:
sv_matrix = np.arange(2, 32)**2
sv_matrix.reshape(6, 5)
# sv_matrix

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

In [339]:
m = np.arange(2,1000)
# m_saknis_bool = m**0.5%1==0
# m_saknis_bool
m_saknis = m[m ** 0.5 % 1 == 0] # kieikvienas skiacius is saraso isimamas is saknio    ** 0.5 (kv.saknis), %1==0 (sveikas skaicius be liekanos)
m_saknis.reshape(5,6)
# m_saknis

array([[  4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169],
       [196, 225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576, 625],
       [676, 729, 784, 841, 900, 961]])

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [298]:
sv_vekt_matrix = np.arange(1,101)
sv_vekt_matrix

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [325]:
def is_pirminis(sk):
    for i in range(2, sk):
        # if sk == 1:
            if sk % i == 0:
                # print(i)
                return False
        # return False
    return True
ar_piprminis = is_pirminis(4)
print(ar_piprminis)

False


In [326]:
nauja_funkcija = np.vectorize(is_pirminis)
nauja_funkcija

In [312]:
new_vekt_matrix= sv_vekt_matrix[nauja_funkcija(sv_vekt_matrix)]
new_vekt_matrix

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])

In [ ]:
#array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
    #    59, 61, 67, 71, 73, 79, 83, 89, 97])