# Numpy

In [300]:
import numpy as np

In [301]:
sarasas = [5,5,8,9,3]
vektorius = np.array(sarasas)
print(vektorius)

[5 5 8 9 3]


In [302]:
sarasai = [
    [4,5,6],
    [1,2,3],
    [7,8,9]
]
matrica = np.matrix(sarasai)
print(matrica)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [303]:
np.arange(0, 78, 7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77])

In [304]:
print(np.arange(0, 78, 7))

[ 0  7 14 21 28 35 42 49 56 63 70 77]


In [305]:
np.zeros(7)


array([0., 0., 0., 0., 0., 0., 0.])

In [306]:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


In [307]:
print(np.zeros((7, 7)))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [308]:
print(np.zeros((7, 7), dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [309]:
print(np.linspace(0,20,9))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


In [310]:
print(np.linspace(0,20,5))

[ 0.  5. 10. 15. 20.]


In [311]:
vienetine = np.eye(7, dtype=int)
vienetine [3,5] = 5
print(vienetine)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 5 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [312]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random array/matricos kurimas

In [313]:
np.random.rand(10)

array([0.50975029, 0.870613  , 0.34836038, 0.11060334, 0.62499478,
       0.93423846, 0.33228151, 0.85657046, 0.46435355, 0.44023083])

In [314]:
print(np.random.rand(3,4))

[[0.54656359 0.68479472 0.32977879 0.20132309]
 [0.67087952 0.08043496 0.52016148 0.76441858]
 [0.64026727 0.37163563 0.40168415 0.12860896]]


In [315]:
print(np.random.randint(-10, 11, 7)) # randINT

[-6  0 -1 -4  3 10 10]


# Masyvu pertvarkymas

In [316]:
masyvas = np.random.randint(-90,100,81)
print(masyvas)
pertvarkyta = masyvas.reshape(9,9)
print(pertvarkyta)

[-47  78  97 -43  16  83  62  65  21 -15  71  43  54   4  27  30 -90 -29
  45 -90 -59 -82  16 -24  17  62 -53  56 -21 -31 -87  52 -34 -37  -9 -31
   0  95  61 -43  62 -85 -46  78   8 -85  65  -9  18  53 -47  60 -35  86
  -3 -90  99 -33   2 -42 -20  34 -74  70  20 -88  67 -28 -63 -71 -49  -4
 -45 -78 -72 -87  81  74 -71   6 -86]
[[-47  78  97 -43  16  83  62  65  21]
 [-15  71  43  54   4  27  30 -90 -29]
 [ 45 -90 -59 -82  16 -24  17  62 -53]
 [ 56 -21 -31 -87  52 -34 -37  -9 -31]
 [  0  95  61 -43  62 -85 -46  78   8]
 [-85  65  -9  18  53 -47  60 -35  86]
 [ -3 -90  99 -33   2 -42 -20  34 -74]
 [ 70  20 -88  67 -28 -63 -71 -49  -4]
 [-45 -78 -72 -87  81  74 -71   6 -86]]


In [317]:
print(pertvarkyta.min())
print(pertvarkyta.max())

-90
99


In [318]:
print(pertvarkyta.argmin())
print(pertvarkyta.argmax())

16
56


In [319]:
print(pertvarkyta.shape)
print(pertvarkyta.dtype)

(9, 9)
int32


In [320]:
print(len(str(2**64)))
print(len(str(2**32)))

20
10


# indeksacija ir reiksmiu traukymas

In [321]:
masyvas[5]

83

In [322]:
masyvas[3:6]

array([-43,  16,  83])

In [323]:
masyvas[::4] = 4


In [324]:
pertvarkyta[0,0]

4

In [325]:
masyvas.reshape(9, 9)

array([[  4,  78,  97, -43,   4,  83,  62,  65,   4],
       [-15,  71,  43,   4,   4,  27,  30,   4, -29],
       [ 45, -90,   4, -82,  16, -24,   4,  62, -53],
       [ 56,   4, -31, -87,  52,   4, -37,  -9, -31],
       [  4,  95,  61, -43,   4, -85, -46,  78,   4],
       [-85,  65,  -9,   4,  53, -47,  60,   4,  86],
       [ -3, -90,   4, -33,   2, -42,   4,  34, -74],
       [ 70,   4, -88,  67, -28,   4, -71, -49,  -4],
       [  4, -78, -72, -87,   4,  74, -71,   6,   4]])

In [326]:
pertvarkyta[1:4, 5:8]

array([[ 27,  30,   4],
       [-24,   4,  62],
       [  4, -37,  -9]])

In [327]:
masyvas=np.random.randint(0,100,100)
matrica = masyvas.reshape(10,10)
print(matrica)


[[84 94  5 33 82 14 14 37 44  8]
 [58 76  2 83 93 81 71  0 71 70]
 [25 12 78  1  9 12 14 33 38 49]
 [70 48 16 45 65 45 31 94 31 33]
 [85 59 68 18 32 61 46 65 82 29]
 [ 3 22 21 11 98  2 87 80 49 17]
 [55 33 68 11 96 91 52 36 48  7]
 [25 50 49 51 61 69 42 59 33 99]
 [90 58 82 74 93 40 76  6 37 79]
 [ 7 85 50  8 46 44 94 39 28 41]]


In [328]:
matrica[::2, ::2] # kas antra sk, kas antra eilute

array([[84,  5, 82, 14, 44],
       [25, 78,  9, 14, 38],
       [85, 68, 32, 46, 82],
       [55, 68, 96, 52, 48],
       [90, 82, 93, 76, 37]])

In [329]:
matrica[-2::-2, -2::-2] # atvirksiai

array([[37, 76, 93, 82, 90],
       [48, 52, 96, 68, 55],
       [82, 46, 32, 68, 85],
       [38, 14,  9, 78, 25],
       [44, 14, 82,  5, 84]])

In [330]:
# tik 1 eilute
matrica[:, 1]

array([94, 76, 12, 48, 59, 22, 33, 50, 58, 85])

In [331]:
# tik 1 eilute
matrica[:, 1]

array([94, 76, 12, 48, 59, 22, 33, 50, 58, 85])

In [332]:
# tik 1 eilute
matrica[:, 1:2]

array([[94],
       [76],
       [12],
       [48],
       [59],
       [22],
       [33],
       [50],
       [58],
       [85]])

# traukymas pagal salyga


In [333]:
masyvas

array([84, 94,  5, 33, 82, 14, 14, 37, 44,  8, 58, 76,  2, 83, 93, 81, 71,
        0, 71, 70, 25, 12, 78,  1,  9, 12, 14, 33, 38, 49, 70, 48, 16, 45,
       65, 45, 31, 94, 31, 33, 85, 59, 68, 18, 32, 61, 46, 65, 82, 29,  3,
       22, 21, 11, 98,  2, 87, 80, 49, 17, 55, 33, 68, 11, 96, 91, 52, 36,
       48,  7, 25, 50, 49, 51, 61, 69, 42, 59, 33, 99, 90, 58, 82, 74, 93,
       40, 76,  6, 37, 79,  7, 85, 50,  8, 46, 44, 94, 39, 28, 41])

In [334]:
masyvas > 30

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False, False,  True, False, False, False, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False, False, False, False, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
        True])

In [335]:
masyvas[masyvas > 30]

array([84, 94, 33, 82, 37, 44, 58, 76, 83, 93, 81, 71, 71, 70, 78, 33, 38,
       49, 70, 48, 45, 65, 45, 31, 94, 31, 33, 85, 59, 68, 32, 61, 46, 65,
       82, 98, 87, 80, 49, 55, 33, 68, 96, 91, 52, 36, 48, 50, 49, 51, 61,
       69, 42, 59, 33, 99, 90, 58, 82, 74, 93, 40, 76, 37, 79, 85, 50, 46,
       44, 94, 39, 41])

In [336]:
iki_30 = masyvas< 30
print(iki_30)

[False False  True False False  True  True False False  True False False
  True False False False False  True False False  True  True False  True
  True  True  True False False False False False  True False False False
 False False False False False False False  True False False False False
 False  True  True  True  True  True False  True False False False  True
 False False False  True False False False False False  True  True False
 False False False False False False False False False False False False
 False False False  True False False  True False False  True False False
 False False  True False]


In [337]:
masyvas[masyvas < 30]

array([ 5, 14, 14,  8,  2,  0, 25, 12,  1,  9, 12, 14, 16, 18, 29,  3, 22,
       21, 11,  2, 17, 11,  7, 25,  6,  7,  8, 28])

In [338]:
masyvas[iki_30] = 30 # kur buvo < 30, perrase i 30
masyvas

array([84, 94, 30, 33, 82, 30, 30, 37, 44, 30, 58, 76, 30, 83, 93, 81, 71,
       30, 71, 70, 30, 30, 78, 30, 30, 30, 30, 33, 38, 49, 70, 48, 30, 45,
       65, 45, 31, 94, 31, 33, 85, 59, 68, 30, 32, 61, 46, 65, 82, 30, 30,
       30, 30, 30, 98, 30, 87, 80, 49, 30, 55, 33, 68, 30, 96, 91, 52, 36,
       48, 30, 30, 50, 49, 51, 61, 69, 42, 59, 33, 99, 90, 58, 82, 74, 93,
       40, 76, 30, 37, 79, 30, 85, 50, 30, 46, 44, 94, 39, 30, 41])

In [339]:
naujas=np.random.randint(0, 100, 20)
# naujas[naujas > 50] = np.random.randint(0, 100)
naujas

array([62, 70, 94, 19, 92, 98, 60, 85, 35, 88, 29, 50, 36, 13, 66, 89, 61,
       15, 93, 39])

In [340]:
naujas[naujas > 50] = np.random.randint(0, 100)
naujas

array([71, 71, 71, 19, 71, 71, 71, 71, 35, 71, 29, 50, 36, 13, 71, 71, 71,
       15, 71, 39])

In [341]:
ispjova = masyvas.copy()[30:60] # padarem kopija, kopijoje pasiimam nuo 30 iki 60 indeksa 
print("masyvas: ", masyvas)
print("ispjova, copy: ", ispjova)
ispjova[:] = 99 # paketem ispjova su 99 reiksmemis
print("perrasyta ispjova: ", ispjova)

masyvas:  [84 94 30 33 82 30 30 37 44 30 58 76 30 83 93 81 71 30 71 70 30 30 78 30
 30 30 30 33 38 49 70 48 30 45 65 45 31 94 31 33 85 59 68 30 32 61 46 65
 82 30 30 30 30 30 98 30 87 80 49 30 55 33 68 30 96 91 52 36 48 30 30 50
 49 51 61 69 42 59 33 99 90 58 82 74 93 40 76 30 37 79 30 85 50 30 46 44
 94 39 30 41]
ispjova, copy:  [70 48 30 45 65 45 31 94 31 33 85 59 68 30 32 61 46 65 82 30 30 30 30 30
 98 30 87 80 49 30]
perrasyta ispjova:  [99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99]


In [342]:
masyvas.copy() == masyvas

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [343]:
#filtravimas nuo 30 iki 60
tarpinis = masyvas[masyvas >= 30]
tarpinis[tarpinis < 60]

array([30, 33, 30, 30, 37, 44, 30, 58, 30, 30, 30, 30, 30, 30, 30, 30, 33,
       38, 49, 48, 30, 45, 45, 31, 31, 33, 59, 30, 32, 46, 30, 30, 30, 30,
       30, 30, 49, 30, 55, 33, 30, 52, 36, 48, 30, 30, 50, 49, 51, 42, 59,
       33, 58, 40, 30, 37, 30, 50, 30, 46, 44, 39, 30, 41])

# Matematines operacijos

In [344]:
vektorius = np.arange(1, 11, 1)
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [345]:
vektorius**vektorius

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408])

In [346]:
vektorius**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [347]:
sarasas

[5, 5, 8, 9, 3]

In [348]:
# sarasas**3 # su sarasu negalima atlykti skaiciavima

In [349]:
vektorius**3 / vektorius

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [350]:
(vektorius+100)/10

array([10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [351]:
vektorius/0

C:\Users\serge\AppData\Local\Temp\ipykernel_8428\1628897937.py:1: RuntimeWarning: divide by zero encountered in divide
  vektorius/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [352]:
np.sin(vektorius)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [353]:
np.tan(vektorius)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [354]:
type(vektorius)

numpy.ndarray

In [355]:
np.log(vektorius**2)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])